// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7TSQewnbo_F7p1MY9WJdnRPs9cysrocY',
    appId: '1:980898244777:web:a576c4ed5095ffd01da1b8',
    messagingSenderId: '980898244777',
    projectId: 'food-app-fcfb2',
    authDomain: 'food-app-fcfb2.firebaseapp.com',
    storageBucket: 'food-app-fcfb2.appspot.com',
    measurementId: 'G-BSWQYC80TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdVeSYiTB52Cb7ZoAKPA-QajqQjAZdsXw',
    appId: '1:980898244777:android:e54dd84afa0cdd6b1da1b8',
    messagingSenderId: '980898244777',
    projectId: 'food-app-fcfb2',
    storageBucket: 'food-app-fcfb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoKnBCIGmqkuhEcz0sSuD-NGYXqn5iPxo',
    appId: '1:980898244777:ios:153226dd2c106db91da1b8',
    messagingSenderId: '980898244777',
    projectId: 'food-app-fcfb2',
    storageBucket: 'food-app-fcfb2.appspot.com',
    androidClientId: '980898244777-2se2o14vlbgafi036q18jpn9rfc65ekv.apps.googleusercontent.com',
    iosClientId: '980898244777-m7qgffvlsc397n70b2sa7h748u79bgnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoKnBCIGmqkuhEcz0sSuD-NGYXqn5iPxo',
    appId: '1:980898244777:ios:153226dd2c106db91da1b8',
    messagingSenderId: '980898244777',
    projectId: 'food-app-fcfb2',
    storageBucket: 'food-app-fcfb2.appspot.com',
    androidClientId: '980898244777-2se2o14vlbgafi036q18jpn9rfc65ekv.apps.googleusercontent.com',
    iosClientId: '980898244777-m7qgffvlsc397n70b2sa7h748u79bgnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7TSQewnbo_F7p1MY9WJdnRPs9cysrocY',
    appId: '1:980898244777:web:2cf5980aae7702d51da1b8',
    messagingSenderId: '980898244777',
    projectId: 'food-app-fcfb2',
    authDomain: 'food-app-fcfb2.firebaseapp.com',
    storageBucket: 'food-app-fcfb2.appspot.com',
    measurementId: 'G-0Y70QTMQHM',
  );
}
